name: Run ESLint on Pull Requests

on:
  - push

jobs:
  build:
    name: Run ESLint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm ci
      - uses: eslint/github-action@v0
